// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW01A42LTjCyV3mhy1a1xYrJ6NzkgjdsQ',
    appId: '1:210611802225:web:5bc53420ff73b5fbe5cbd0',
    messagingSenderId: '210611802225',
    projectId: 'maya-app-cymake',
    authDomain: 'maya-app-cymake.firebaseapp.com',
    storageBucket: 'maya-app-cymake.firebasestorage.app',
    measurementId: 'G-YPC7NYVSRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdpSpBQZ5uqTcNhv4EMqU64xKS8e_ns1Y',
    appId: '1:210611802225:android:51ae7f37958222dde5cbd0',
    messagingSenderId: '210611802225',
    projectId: 'maya-app-cymake',
    storageBucket: 'maya-app-cymake.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYLneOggw4AxxGmTzqGv8CWiuXyq8oyLk',
    appId: '1:210611802225:ios:c05d9d37d1eb900ee5cbd0',
    messagingSenderId: '210611802225',
    projectId: 'maya-app-cymake',
    storageBucket: 'maya-app-cymake.firebasestorage.app',
    iosBundleId: 'com.ravan.maya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYLneOggw4AxxGmTzqGv8CWiuXyq8oyLk',
    appId: '1:210611802225:ios:c05d9d37d1eb900ee5cbd0',
    messagingSenderId: '210611802225',
    projectId: 'maya-app-cymake',
    storageBucket: 'maya-app-cymake.firebasestorage.app',
    iosBundleId: 'com.ravan.maya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW01A42LTjCyV3mhy1a1xYrJ6NzkgjdsQ',
    appId: '1:210611802225:web:dbc8569875da685fe5cbd0',
    messagingSenderId: '210611802225',
    projectId: 'maya-app-cymake',
    authDomain: 'maya-app-cymake.firebaseapp.com',
    storageBucket: 'maya-app-cymake.firebasestorage.app',
    measurementId: 'G-YJ4SPT8TPS',
  );

}